In [3]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [9]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [10]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [12]:
array_example.ndim

3

In [13]:
array_example.size

24

In [14]:
array_example.shape

(3, 2, 4)

In [15]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [16]:
arr_one.shape

(1, 5)

In [17]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [18]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [19]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [20]:
np.newaxis
np.expand_dims

<function numpy.expand_dims(a, axis)>

In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [22]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [23]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:

# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [25]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [26]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [27]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [28]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [30]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [31]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [32]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [33]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [34]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [35]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [36]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [37]:

# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [38]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [40]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [41]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [42]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [43]:
data = np.array([1, 2])
data

array([1, 2])

In [44]:
ones = np.ones(2)
ones

array([1., 1.])

In [45]:
data * 2

array([2, 4])

In [46]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [47]:
A.sum()

4.8595784

In [48]:
A.min()

0.05093587

In [49]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [50]:
A.max()

0.82485143

In [51]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [52]:
A.std()

0.21392120766089617

In [53]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.09701047, 0.43990836],
       [0.38105461, 0.60943102],
       [0.989207  , 0.72626741]])

In [54]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.83255871 0.81447338]
 [0.75392595 0.32148495]
 [0.63250475 0.69671404]]


In [55]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [56]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [57]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [58]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [59]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [60]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [61]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [62]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [63]:
print(data.max())
print(data.min())
print(data.sum())


6
1
21


In [64]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [65]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [66]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [67]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [68]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [69]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [70]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [71]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [72]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [73]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [74]:
print(np.random.random((4,3,2)))

[[[0.81744197 0.13399375]
  [0.38742998 0.30106003]
  [0.51242751 0.01904505]]

 [[0.3205291  0.65574892]
  [0.60417019 0.93706783]
  [0.34851948 0.3975257 ]]

 [[0.7732067  0.55707276]
  [0.4104059  0.1348497 ]
  [0.58954247 0.86122088]]

 [[0.40626552 0.55799409]
  [0.04797834 0.70223348]
  [0.37131462 0.71896768]]]


In [75]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [76]:
# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
a = np.arange(mulai,selesai)
b = np.array(a)
print(b)

Mulai : 1
Selesai : 28
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27]


In [78]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
a = np.arange(mulai,selesai)
b = a.reshape(3,9)

print(b)

Mulai : 1
Selesai : 28
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


In [79]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
a = np.arange(mulai,selesai)
b = a.reshape(9,3)

print(b)

Mulai : 1
Selesai : 28
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]]


In [80]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
data = np.arange(mulai,selesai)
data

Mulai : 1
Selesai : 28


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [81]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
data2 = np.arange(mulai,selesai)
pecah = data2.reshape(3,9)
pecah

Mulai : 1
Selesai : 28


array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [82]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
data3 = np.arange(mulai,selesai)
pecah3 = data3.reshape(3,3,3)
pecah3

Mulai : 1
Selesai : 28


array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [86]:
n = int(input("Banyak Data : "))
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
datarandom = np.random.randint(mulai,selesai, n)
datarandom

Banyak Data : 16
Mulai : 1
Selesai : 50


array([41, 41, 16, 29, 18,  7, 43,  6,  7, 16, 29,  4, 40, 49, 14, 47])

In [87]:
#dua dimensi
dataduadimensi = datarandom.reshape(4,4)
dataduadimensi

array([[41, 41, 16, 29],
       [18,  7, 43,  6],
       [ 7, 16, 29,  4],
       [40, 49, 14, 47]])

In [90]:
#tukar posisi
dataduadimensi[:,::-1]


array([[29, 16, 41, 41],
       [ 6, 43,  7, 18],
       [ 4, 29, 16,  7],
       [47, 14, 49, 40]])

In [91]:
#array 2 dimensi 10 x 10
x = np.ones((10,10))*4
x[1:-1,1:-1]=0
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])