In [3]:
conda install numpy

Solving environment: ...working... done

# All requested packages already installed.


Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

a = np.array([1, 2, 3])

In [5]:
a

array([1, 2, 3])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [11]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [12]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [15]:
array_example.ndim

3

In [16]:
array_example.size

24

In [17]:
array_example.shape

(3, 2, 4)

In [18]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [20]:
arr_one.shape

(1, 5)

In [21]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [22]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [23]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [24]:
np.newaxis
np.expand_dims

<function numpy.expand_dims(a, axis)>

In [25]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [26]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [27]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [28]:

# You can easily print all of the values in the array that are less than 5

print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [29]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [30]:
# You can select elements that are divisible by 2

divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [31]:
# you can select elements that satisfy two conditions using the & and | operators

c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


In [32]:
arr = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [36]:
a_1 = np.array([[1, 1],
                [2, 2]])

In [37]:
a_2 = np.array([[3, 3],
                [4, 4]])

In [38]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [39]:
# Or stack them horizontally with hstack

np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [41]:
arrsplit = np.array([[1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [42]:
# If you wanted to split this array into three equally shaped arrays

np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [43]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:

# You can create a new array object that looks at the same data

b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [45]:
# Using the copy method will make a complete copy of the array and its data (a deep copy).

c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
a = np.array([1, 2, 3, 4])

# Add all of the elements in the array
a.sum()

10

In [47]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [48]:
# You can sum the rows

b.sum(axis=0)

array([3, 3])

In [49]:
# You can sum the columns

b.sum(axis=1)

array([2, 4])

In [50]:
data = np.array([1, 2])
data

array([1, 2])

In [51]:
ones = np.ones(2)
ones

array([1., 1.])

In [52]:
data * 2

array([2, 4])

In [53]:
A = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(A)

[[0.45053314 0.17296777 0.34376245 0.5510652 ]
 [0.54627315 0.05093587 0.40067661 0.55645993]
 [0.12697628 0.82485143 0.26590556 0.56917101]]


In [55]:
A.sum()

4.8595784

In [56]:
A.min()

0.05093587

In [57]:
A.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [58]:
A.max()

0.82485143

In [59]:
A.max(axis=1)

array([0.5510652 , 0.55645993, 0.82485143])

In [60]:
A.std()

0.21392120766089617

In [61]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.58542562, 0.92700498],
       [0.36737594, 0.958162  ],
       [0.35291009, 0.87571722]])

In [62]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.4912787  0.23312031]
 [0.48044435 0.34722484]
 [0.08887515 0.20652626]]


In [63]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [64]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [65]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [66]:
ones_row = np.ones([1, 2])
print(ones_row)

[[1. 1.]]


In [67]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [68]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [69]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


In [70]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [71]:
print(data.max())
print(data.min())
print(data.sum())


6
1
21


In [72]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


In [73]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [74]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [75]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [76]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [78]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [79]:
ndarr = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [80]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [81]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [82]:
print(np.random.random((4,3,2)))

[[[0.86902014 0.70678325]
  [0.89882113 0.260217  ]
  [0.91849622 0.720413  ]]

 [[0.01730299 0.82861647]
  [0.18953398 0.58093485]
  [0.58463058 0.56172262]]

 [[0.63589535 0.64213143]
  [0.6199083  0.72036802]
  [0.03056174 0.25748959]]

 [[0.64311203 0.29854068]
  [0.63345136 0.06838379]
  [0.78801149 0.87765582]]]


In [83]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [84]:
# You can use flatten to flatten your array into a 1D array.

arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [133]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
a = np.arange(mulai,selesai)
b = np.array(a)
print(b)

Mulai : 1
Selesai : 28
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]


In [141]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
a = np.arange(mulai,selesai)
b = a.reshape(3,9)

print(b)

Mulai : 1
Selesai : 28
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


In [144]:
mulai = int(input("Mulai : "))
selesai = int(input("Selesai : "))
a = np.arange(mulai,selesai)
np.hsplit(a,3)


Mulai : 1
Selesai : 28


[array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18]),
 array([19, 20, 21, 22, 23, 24, 25, 26, 27])]